### ISSUE TITLE
Where is distance.h?

### ISSUE THREAD

**Issue by CaucherWang** [csypeng/taumng_sigmod#1]
You use ` float dist = distance_->compare_by_loop(data_ + dimension_ * id, query, (unsigned)dimension_);` in your codes. But I don't find the definition of compare_by_loop in your code or in NSG's code.

**Comment by CaucherWang** [comment]
I guess you forgot to upload distance.h.

**Comment by CaucherWang** [comment]
Besides, the definition of DFS in TauMNG is missing. Is it the same as NSG?

**Comment by csypeng** [comment]
distance.h is uploaded.

**Comment by csypeng** [comment]
> Besides, the definition of DFS in TauMNG is missing. Is it the same as NSG?

Yes.
